<a href="https://colab.research.google.com/github/GeoLabUniLaSalle/Python/blob/main/6_7_Part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


## **Data Science**
Machine Learning

# **PyTorch: Facebook's deep learning library**
Lyes LAKHAL
lyes.lakhal@unilasalle.fr








# All machine learning is concerned with extracting information from data. So we will begin by learning the practical skills for storing, manipulating, and preprocessing data with PyTorch, the Facebook's deep learning library.


# **1. Data Manipulation**


# **1.1 Getting Started**



**To start, we import `torch`.**


In [ ]:
import torch

A tensor represents a (possibly multi-dimensional) array of numerical values
With one axis, a tensor corresponds (in math) to a *vector*.
With two axes, a tensor corresponds to a *matrix*.
Tensors with more than two axes do not have special
mathematical names.

To start, we can use `arange` to create a row vector `x`
containing the first 12 integers starting with 0,
though they are created as floats by default.
Each of the values in a tensor is called an *element* of the tensor.


In [ ]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

**We can access a tensor's *shape*** (the length along each axis)
by inspecting its `shape` property.


In [ ]:
x.shape

torch.Size([12])

If we just want to know the total number of elements in a tensor,
we can inspect its size.
Because we are dealing with a vector here,
the single element of its `shape` is identical to its size.


In [ ]:
x.numel()

12

To change the shape of a tensor without altering
either the number of elements or their values,
we can invoke the `reshape` function.



In [ ]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Create a tensor with all elements
set to 0 and a shape of (2, 3, 4) :


In [ ]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

Similarly, we can create tensors with each element set to 1 as follows:


In [ ]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

Creates a tensor with shape (3, 4) with elements randomly sampled
from a standard Gaussian (normal) distribution
with a mean of 0 and a standard deviation of 1.


In [ ]:
torch.randn(3, 4)

tensor([[-0.1897, -1.0606,  2.1862,  0.8286],
        [-0.7529,  1.0529, -0.9317, -0.1295],
        [ 0.4705,  0.0611,  0.9392, -0.9576]])

We can also specify the exact values for each element in the desired tensor
by supplying a Python list (or list of lists) containing the numerical values.
**Here, the outermost list corresponds to axis 0, and the inner list to axis 1.**


In [ ]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

# **1.2. Operations**

The common standard arithmetic operators
(`+`, `-`, `*`, `/`, and `**`)
have all been *lifted* to elementwise operations.


In [ ]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x**y  # The ** operator is exponentiation

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

Many **more operations can be applied elementwise**,
including unary operators like exponentiation.


In [ ]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

We can also concatenate multiple tensors together,
stacking them end-to-end to form a larger tensor.


In [ ]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0) 

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [ ]:
torch.cat((X, Y), dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

Sometimes, we want to construct a binary tensor via *logical statements*.
Take `X == Y` as an example.



In [ ]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

**Summing all the elements in the tensor** yields a tensor with only one element.


In [ ]:
X.sum()

tensor(66.)

# **1.3 Broadcasting Mechanism (*to be deeply understand* !)**


In the above section, we saw how to perform elementwise operations
on two tensors of the same shape. Under certain conditions (when one of the dimensions of the tensor is 1), even when shapes differ, we can still perform elementwise operations by invoking the *broadcasting mechanism*.




In [ ]:
a = torch.arange(8).reshape((8,1))
b = torch.arange(6).reshape((1,6))
a, b

(tensor([[0],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7]]), tensor([[0, 1, 2, 3, 4, 5]]))

Since `a` and `b` are $3\times1$ and $1\times2$ matrices respectively,
their shapes do not match up if we want to add them.
We *broadcast* the entries of both matrices into a larger $3\times2$ matrix as follows:
for matrix `a` it replicates the columns
and for matrix `b` it replicates the rows
before adding up both elementwise.


In [ ]:
a + b

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 1,  2,  3,  4,  5,  6],
        [ 2,  3,  4,  5,  6,  7],
        [ 3,  4,  5,  6,  7,  8],
        [ 4,  5,  6,  7,  8,  9],
        [ 5,  6,  7,  8,  9, 10],
        [ 6,  7,  8,  9, 10, 11],
        [ 7,  8,  9, 10, 11, 12]])

# **1.4. Indexing and Slicing**

Just as in any other Python array, elements in a tensor can be accessed by index.


Thus, `[-1]` selects the last element and `[1:3]`
selects the second and the third elements as follows:


In [ ]:
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
X[-1], X[1:3]

(tensor([ 8,  9, 10, 11]), tensor([[ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]))

Beyond reading, (**we can also write elements of a matrix by specifying indices.**)


In [ ]:
X[1, 2] = 9
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  9,  7],
        [ 8,  9, 10, 11]])

If we want [**to assign multiple elements the same value,
we simply index all of them and then assign them the value.**]
For instance, `[0:2, :]` accesses the first and second rows,
where `:` takes all the elements along axis 1 (column).
While we discussed indexing for matrices,
this obviously also works for vectors
and for tensors of more than 2 dimensions.


In [ ]:
X[0:2, :] = 12
X

tensor([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [ 8,  9, 10, 11]])

# **1.5 Conversion to Other Python Objects**


Converting to a NumPy tensor (`ndarray`), or vice versa, is easy.
The torch Tensor and numpy array will share their underlying memory
locations, and changing one through an in-place operation will also
change the other.


In [ ]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

To convert a size-1 tensor to a Python scalar,
we can invoke the `item` function or Python's built-in functions.


In [ ]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)