<a href="https://colab.research.google.com/github/GeoLabUniLaSalle/Python/blob/main/Les_tableaux.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Les tableaux**

Dans ce chapitre, nous allons étudier le fonctionnement du module NumPy qui permet de travailler avec des tableaux multidimensionnels/matrices et de réaliser différentes opérations mathématiques.

Les tableaux sont **mutables** et **homogènes**.

Commençons par importer le module NumPy.

In [2]:
import numpy as np

En cas d'erreur sur cette ligne, lancez l'installation du module numpy, redémarrez le noyau, puis re-exécutez l'import du module.

In [ ]:
import sys  
!{sys.executable} -m pip install --user numpy

Créons un premier tableau à partir d'une liste.

In [1]:

v = np.array([7,0,-1,5])
print(v)
print(type(v)) 

[ 7  0 -1  5]
<class 'numpy.ndarray'>


Le type de données associé aux tableaux est *numpy.darray*.

Créons maintenant un tableau à 2 dimensions et accédons à son contenu.

In [ ]:
M = np.array([[7, 0], [-1, 5]])
print(M)
print(M[0,0])
print(M[1,1])
print(type(M))

[[ 7  0]
 [-1  5]]
7
5
<class 'numpy.ndarray'>


L'opérateur *shape* permet de connaite la taille d'un tableau, qui est retourné sous la forme d'un *tuple*.

In [ ]:
print(v.shape)
print(M.shape)
print(type(M.shape))

(4,)
(2, 2)
<class 'tuple'>


L'opérateur *ndim* permet de connaitre le nombre de dimensions d'un tableau.

In [ ]:
print(v.ndim)
print(M.ndim)

1
2


L'opérateur *size* permet de connaitre le nombre d'éléments d'un tableau.



In [ ]:
print(v.size)
print(M.size) 

4
4


L'opérateur *dtype* permet de connaitre le type des éléments d'un tableau.



In [ ]:
print(v.dtype)
print(M.dtype)

int64
int64


Ici, nous avons des entiers codés sur 64 bits (valeur pouvant aller de -2^63 à +2^63).

L'opérateur *itemsize* permet de connaitre le poides des éléments d'un tableau, en octets.

In [ ]:
print(v.itemsize)
print(M.itemsize)

8
8


Les élements ont une taille de 8 octets (byte). Nous retrouvons le résultat précédent puisque 1 octet est composé de 8 bits. 

Enfin, l'opérateur *nbytes* permet de connaître le poids total d'un tableau, en octets.

In [ ]:
print(v.nbytes)
print(M.nbytes)

32
32


Les deux tableaux contienent 4 éléments pesant chacun 8 octets. Leur poids total est identique : 32 octets (4 x 8 octets).

Vérifions maintenant que les tableaux sont bien **mutables**.


In [ ]:
print(M)
M[0,0] = 3
print(M)

[[ 7  0]
 [-1  5]]
[[ 3  0]
 [-1  5]]


Vérifions également que les tableaux sont bien **homogènes**.

In [ ]:
print(M)
M[0,0] = 'bonjour'
print(M)

[[ 3  0]
 [-1  5]]


ValueError: ignored

Lors de la création d'un tableau, il est possible de choisir le type de ses éléments.

In [ ]:
M = np.array([[7, 0], [-1, 5]], dtype=np.float64)
M[0,0] = 7.4
print(M)

[[ 7.4  0. ]
 [-1.   5. ]]


Un tableau peut changer de type.

In [ ]:
M = np.array([[7, 0], [-1, 5]])
print(M)
print(M.dtype)
M = M.astype(float)
print(M)
print(M.dtype)

[[ 7  0]
 [-1  5]]
int64
[[ 7.  0.]
 [-1.  5.]]
float64


Ou encore.

In [ ]:
M = np.array([[7, 0], [-1, 5]])
print(M)
print(M.dtype)
M = M.astype(bool)
print(M)
print(M.dtype)

[[ 7  0]
 [-1  5]]
int64
[[ True False]
 [ True  True]]
bool


Il est possible de créer un tableau à partir d'une suite de nombres.

In [ ]:
x = np.array(range(0,10,2))
print(x)

[0 2 4 6 8]


La fonction *numpy.arange()* génère directement un tableau et accepte des arguments flottants.

In [ ]:
x = np.arange(0,10,2)
print(x)

y = np.arange(0,10,0.1)
print(y)

[0 2 4 6 8]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3
 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1
 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.  8.1 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9
 9.  9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]


La fonction *numpy.linspace()* génère un tableau de nombres régulièrement espacés dans un intervalle.

In [ ]:
x = np.linspace(0,10,6)
print(x)

[ 0.  2.  4.  6.  8. 10.]


Voyons comment accéder aux éléments d'un tableau.

In [ ]:
M = np.array([[7, 0], [-1, 5]])
print('M :',M)
print('M[0, 1] :',M[0, 1]) # Affiche l'élément présent en ligne 0, colonne 1
print('M[0] :',M[0]) # Affiche tous les éléments de la ligne 0
print('M[1,:] :',M[1,:]) # Affiche tous les éléments de la ligne 1
print('M[:,1] :',M[:,1]) # Affiche tous les éléments de la colonne 1

M : [[ 7  0]
 [-1  5]]
M[0, 1] : 0
M[0] : [7 0]
M[1,:] : [-1  5]
M[:,1] : [0 5]


Voyons comment modifier le contenu d'un tableau

In [ ]:
M = np.array([[7, 0], [-1, 5]])
M[0,0] = 6 # On place la valeur 6 en ligne 0, colonne 0
print(M)
M[1,:] = 8 # On place la valeur 8 dans toutes les cases de la ligne 1
print(M)
M[:,1] = (3,4) # On place les valeurs 3 et 5 dans les cases de la colonne 1
print(M)

[[ 6  0]
 [-1  5]]
[[6 0]
 [8 8]]
[[6 3]
 [8 4]]


Il est possible de slice un tableau.

In [ ]:
A = np.array([1, 2, 3, 4, 5])
print(A) # Tous les éléments
print(A[1:3]) # Les éléments d'indice 1 à 2 (3 exclu)
print(A[::]) # Tous les éléments
print(A[::2]) # Tous les éléments avec un pas de 2
print(A[:3]) # Tous les éléments jusqu'à celui d'indice 2 (3 exclu)
print(A[3:]) # Tous les éléments à partir de l'indice 3
print(A[-1]) # Le dernier élément
print(A[-3:]) # Les 3 derniers éléments

[1 2 3 4 5]
[2 3]
[1 2 3 4 5]
[1 3 5]
[1 2 3]
[4 5]
5
[3 4 5]


Construisons un tableau à partir d'une liste générée avec une boucle.

In [ ]:
l = []
for m in range(4):
  c = []
  for n in range(4):
    c.append(n+m*10)
  l.append(c)
A = np.array(l)
# Peut aussi s'écrire A = np.array([[n + m * 10 for n in range(4)] for m in range(4)])
print(A)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]]


Accédons enfin à une partie des données.

In [ ]:
print(A[1:3, 1:3]) # Elements sur les lignes d'indice 1 et 2 (3 exclu) et colonnes d'indice 1 et 2 (3 exclu)
print(A[::2, ::2]) # Tous les éléments, avec un pas de 2 sur les lignes et sur les colonnes

[[11 12]
 [21 22]]
[[ 0  2]
 [20 22]]
