<a href="https://colab.research.google.com/github/GeoLabUniLaSalle/Python/blob/main/Manipuler_les_tableaux.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Manipuler les tableaux**

Dans ce chapitre, nous allons réaliser du calcul matriciel grâce au module NumPy qui permet de travailler avec des tableaux multidimensionnels/matrices.


Commençons par importer le module NumPy.


In [ ]:
import numpy as np

En cas d'erreur sur cette ligne, lancez l'installation du module numpy, redémarrez le noyau, puis re-exécutez l'import du module.

In [ ]:
import sys  
!{sys.executable} -m pip install --user numpy

Créons un premier tableau à partir d'une liste.

In [ ]:
a = np.arange(5, dtype=float)
print(a)

[0. 1. 2. 3. 4.]


En cas d'erreur sur ce bloc d'instructions, lancez l'installation du module matplotlib, redémarrez le noyau, puis re-exécutez la dernière cellule de code.

Réalisons maintenant quelques opérations basiques.

In [ ]:
print(a + 1)
print(2 * a)
print(a ** 2)
print(a + a)
print(a * a)

[1. 2. 3. 4. 5.]
[0. 2. 4. 6. 8.]
[ 0.  1.  4.  9. 16.]
[0. 2. 4. 6. 8.]
[ 0.  1.  4.  9. 16.]


Il est possible de réaliser des calculs avec les éléments de 2 tableaux.

In [ ]:
a = np.array([2, 4])
b = np.array([7, 8])
print(a/b)
print(a//b)

[0.28571429 0.5       ]
[0 0]


Construisons une matrice avec des éléments aléatoires compris entre 0 et 1 avec un tirage uniforme grâce au module random.

In [ ]:
M = np.random.random_sample((3, 3))
print(M)

[[0.0967705  0.74950087 0.99089962]
 [0.74142837 0.68231353 0.61931616]
 [0.20591362 0.70852023 0.09888867]]


Construisons une nouvelle matrice contenant des éléments aléatoires compris entre 0 et 1 avec un tirage suivant une loi normale standard (gaussienne centrée normée).

In [ ]:
M = np.random.standard_normal((3, 3))
print(M)

[[ 0.3754451  -0.45102459  0.2687735 ]
 [ 0.15052498 -1.72212515  0.39019252]
 [ 0.55040801  0.8833739   0.53934318]]


Construisons une matrice remplie de 0.

In [ ]:
A = np.zeros((2, 3))
print(A)
print(A.dtype)

[[0. 0. 0.]
 [0. 0. 0.]]
float64


Construisons une matrice remplie de 0, de type entier.

In [ ]:
A = np.zeros((2, 3), dtype=int)
print(A)
print(A.dtype)

[[0 0 0]
 [0 0 0]]
int64


Construisons une matrice remplie de 1.

In [ ]:
A = np.ones((3, 3))
print(A)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Construisons une matrice diagonale à partir d'une liste à une dimension.

In [ ]:
D = np.diag([1, 2, 3])
print(D)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


Extrayons la diagonale d'une matrice.

In [ ]:
l = np.diag(D)
print(l)
print(type(l))

[1 2 3]


La diagonale est retournée sous la forme d'un tableau.

Réalisons une nouvelle matrice.

In [ ]:
l = []
for m in range(4):
  c = []
  for n in range(4):
    c.append(n+m*10)
  l.append(c)
A = np.array(l)
print(A)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]]


Réalisons la transposée de cette matrice.

In [ ]:
print(A.T)

[[ 0 10 20 30]
 [ 1 11 21 31]
 [ 2 12 22 32]
 [ 3 13 23 33]]


Réalisons la somme de cette matrice et de sa transposée.

In [ ]:
print(A+A.T)

[[ 0 11 22 33]
 [11 22 33 44]
 [22 33 44 55]
 [33 44 55 66]]


Réalisons la trace (somme des éléments diagonaux) de la matrice A.

In [ ]:
print(np.trace(A))

66


Réalisons la multiplication, élément par élément, de A par A.

In [ ]:
print(A * A)

[[   0    1    4    9]
 [ 100  121  144  169]
 [ 400  441  484  529]
 [ 900  961 1024 1089]]


Réalisons le produit matriciel de A par A.

In [ ]:
print(np.dot(A, A))

[[ 140  146  152  158]
 [ 740  786  832  878]
 [1340 1426 1512 1598]
 [1940 2066 2192 2318]]


Essayons de réaliser le produit de 2 matrices de dimensions différentes.

In [ ]:
v = np.array([1, 2, 3, 4, 5])
print(v)
print(np.dot(A, v))

[1 2 3 4 5]


ValueError: ignored

Cette opération est impossible parce que la matrice v est incompatible avec la matrice A (elle contient 5 éléments).

Rendons la matrice v compatible pour réaliser le produit matriciel de A par v.

In [ ]:
print(np.dot(A, v[:4]))

[ 20 120 220 320]


Inversons une matrice aléatoire B.

In [ ]:
B = np.random.standard_normal((3, 3))
print(B)
inv = np.linalg.inv(B)
print(inv)

[[-1.40792954  0.07016109  1.28598934]
 [-0.17353153  0.18019434  0.17469442]
 [ 1.76972955 -1.07579654  0.71176396]]
[[-0.5406463   2.45092917  0.37526728]
 [-0.73981857  5.60489662 -0.03898118]
 [ 0.22606298  2.37753909  0.41297764]]


Réalisons enfin le produit de B par son inverse pour retrouver la matrice identité (aux erreurs d'arrondis près).

In [ ]:
print(np.dot(B, inv))

[[ 1.00000000e+00 -8.61196386e-16 -1.90023439e-17]
 [-2.12753324e-19  1.00000000e+00 -3.22534676e-17]
 [-7.69506246e-17  4.96751135e-17  1.00000000e+00]]
